// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrAndMissUniversity.DbUtils;

#nullable disable

namespace MrAndMissUniversity.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260125174914_Initial02")]
    partial class Initial02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MrAndMissUniversity.DbUtils.Student", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BriefIntroduction")
                        .HasColumnType("TEXT");

                    b.Property<short>("EditColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfSpecialty")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photograph")
                        .HasColumnType("BLOB");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<short>("RegistrationStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartDeleteMessage")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelegramId");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
